### PR TITLE
fix(reloader): reload every workload on config change

### PR DESCRIPTION
**Pull request by MrStarktastic**
Fixes the `API Error: Failed to authenticate with Filebrowser` left over after #1092, then fixes the reason it was possible.

### Cause

Both homepage dashboards mount config with `subPath`:

```yaml
globalMounts:
  - path: /app/config/services.yaml
    subPath: services.yaml
```

Kubernetes does not propagate ConfigMap updates into `subPath` mounts — the file in a running pod is frozen at creation. #1092 removed the Filebrowser widget, Argo updated the ConfigMap, and the pod kept serving the old `services.yaml`, so the widget went on calling `/api/login`, which Quantum does not implement. Waiting would never have fixed it; only a pod restart would.

### Why this is broader than homepage

Reloader has been opt-in since #1047 (`autoReloadAll: false`). **27 workloads mount a ConfigMap or Secret and exactly 2 had opted in** — `ntfy` and `filebrowser`. Homepage was simply the one that broke visibly. Annotating apps one bug at a time sets the same trap 25 more times, so this flips the default instead.

### Changes

| File | Change |
|------|--------|
| `infrastructure/system/reloader/values.yaml` | `autoReloadAll: true`, `ignoreNamespaces: monitoring` |
| `bootstrap/appsets/cluster-apps.yaml` | `ignoreDifferences` blocks for `StatefulSet` and `DaemonSet` |
| `ntfy`, `filebrowser`, `homepage-admin` values | drop the now-redundant annotations |

Opt a workload out with `reloader.stakater.com/auto: "false"`.

### The StatefulSet/DaemonSet blocks are load-bearing

`cluster-apps.yaml` only ignored Reloader's `last-reloaded-from` annotation on `kind: Deployment`, with a comment saying to add StatefulSet/DaemonSet blocks if a workload of those kinds was ever annotated. `autoReloadAll` annotates all of them at once — Traefik is a DaemonSet, and the monitoring and logging charts generate both kinds. Without these blocks those apps stamp an annotation Argo does not ignore and sit permanently OutOfSync.

### Why monitoring is excluded

Prometheus and Alertmanager already hot-reload through their config-reloader sidecars. A Reloader restart there is redundant and costs a WAL replay.

Traefik and Authentik stay in scope deliberately: both restart only when a mounted secret is deliberately rotated, and both need the restart to pick it up. Traefik is a DaemonSet, so it rolls per-node rather than dropping ingress wholesale.

### Verification

Rendered flags:

```
--namespaces-to-ignore=monitoring
--reload-strategy=annotations
--auto-reload-all=true
```

`ignoreDifferences` after the change:

```
Secret           -> 1 expr
apps Deployment  -> 3 expr
apps StatefulSet -> 1 expr
apps DaemonSet   -> 1 expr
```

Checked for non-deterministic rendered config that would restart pods on every sync — no `randAlphaNum`, `uuidv4`, `genCA` or `now` anywhere in the repo, so there is none.

`yamllint` clean, homepage coverage `OK: 48 hosts, both dashboards consistent`, no `reloader.stakater.com/auto` annotations left outside the reloader chart itself.

### After merging

**A sync alone will not fix the stale widget.** This PR leaves `homepage-admin`'s Deployment byte-identical to main (the branch adds the annotation, then removes it again once `autoReloadAll` makes it redundant), so there is nothing for Argo to roll. Reloader only acts on a *future* ConfigMap change, and the change that removed the widget already happened in #1092.

So restart `homepage-admin` once by hand — Argo's Restart action on the Deployment, or `kubectl rollout restart`. That clears the stale `services.yaml`. Every config change after this reloads on its own, which is the whole point.

The rest of the change is inert until something actually changes: the flags take effect on the next Reloader sync, and no workload restarts merely because `autoReloadAll` flipped.

### CODE REVIEW

**Comment by MrStarktastic** [comment]
### Note: the diff preview understates this change

The preview reports `Modified (1): homepage-admin (+2)`, but `homepage` is affected too. It just never got rendered.

`AUTO_DETECT_FILES_CHANGED=true` picks Applications from changed file paths, and it doesn't follow `baseApp`. `homepage` sets `baseApp: services/operations/homepage-admin` with `valuesOverride: true`, so per `cluster-apps.yaml:116-138` its `valueFiles` are:

```
templates/globals.yaml
templates/common.yaml
services/operations/homepage-admin/values.yaml   <- the file this PR changes
services/operations/homepage/values.yaml
```

The stats line confirms it only rendered one app: `[Applications: 2]` here versus `[Applications: 148]` on #1092, i.e. apps × 2 branches — so 1 app, not 2.

Rendered `homepage` manually through that exact file order, before and after:

```diff
49a50,51
>   annotations:
>     reloader.stakater.com/auto: "true"
```

On the Deployment, with `app.kubernetes.io/instance: homepage`. So both dashboards get the annotation from this one-line change, which is the intent.

Worth knowing generally: **any** change to a `baseApp`'s `values.yaml` will under-report its blast radius in the diff preview.
